# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /fs03/share/users/theo.louvet/home/Documents/tp_volume_rendering

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /fs03/share/users/theo.louvet/home/Documents/tp_volume_rendering

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /fs03/share/users/theo.louvet/home/Documents/tp_volume_rendering/CMakeFiles /fs03/share/users/theo.louvet/home/Documents/tp_volume_rendering/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /fs03/share/users/theo.louvet/home/Documents/tp_volume_rendering/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pgm

# Build rule for target.
pgm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pgm
.PHONY : pgm

# fast build rule for target.
pgm/fast:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/build
.PHONY : pgm/fast

projet/src/image/color.o: projet/src/image/color.cpp.o
.PHONY : projet/src/image/color.o

# target to build an object file
projet/src/image/color.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/color.cpp.o
.PHONY : projet/src/image/color.cpp.o

projet/src/image/color.i: projet/src/image/color.cpp.i
.PHONY : projet/src/image/color.i

# target to preprocess a source file
projet/src/image/color.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/color.cpp.i
.PHONY : projet/src/image/color.cpp.i

projet/src/image/color.s: projet/src/image/color.cpp.s
.PHONY : projet/src/image/color.s

# target to generate assembly for a file
projet/src/image/color.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/color.cpp.s
.PHONY : projet/src/image/color.cpp.s

projet/src/image/image.o: projet/src/image/image.cpp.o
.PHONY : projet/src/image/image.o

# target to build an object file
projet/src/image/image.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/image.cpp.o
.PHONY : projet/src/image/image.cpp.o

projet/src/image/image.i: projet/src/image/image.cpp.i
.PHONY : projet/src/image/image.i

# target to preprocess a source file
projet/src/image/image.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/image.cpp.i
.PHONY : projet/src/image/image.cpp.i

projet/src/image/image.s: projet/src/image/image.cpp.s
.PHONY : projet/src/image/image.s

# target to generate assembly for a file
projet/src/image/image.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/image.cpp.s
.PHONY : projet/src/image/image.cpp.s

projet/src/image/image_zbuffer.o: projet/src/image/image_zbuffer.cpp.o
.PHONY : projet/src/image/image_zbuffer.o

# target to build an object file
projet/src/image/image_zbuffer.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/image_zbuffer.cpp.o
.PHONY : projet/src/image/image_zbuffer.cpp.o

projet/src/image/image_zbuffer.i: projet/src/image/image_zbuffer.cpp.i
.PHONY : projet/src/image/image_zbuffer.i

# target to preprocess a source file
projet/src/image/image_zbuffer.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/image_zbuffer.cpp.i
.PHONY : projet/src/image/image_zbuffer.cpp.i

projet/src/image/image_zbuffer.s: projet/src/image/image_zbuffer.cpp.s
.PHONY : projet/src/image/image_zbuffer.s

# target to generate assembly for a file
projet/src/image/image_zbuffer.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/image_zbuffer.cpp.s
.PHONY : projet/src/image/image_zbuffer.cpp.s

projet/src/image/io/image_ppm.o: projet/src/image/io/image_ppm.cpp.o
.PHONY : projet/src/image/io/image_ppm.o

# target to build an object file
projet/src/image/io/image_ppm.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/io/image_ppm.cpp.o
.PHONY : projet/src/image/io/image_ppm.cpp.o

projet/src/image/io/image_ppm.i: projet/src/image/io/image_ppm.cpp.i
.PHONY : projet/src/image/io/image_ppm.i

# target to preprocess a source file
projet/src/image/io/image_ppm.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/io/image_ppm.cpp.i
.PHONY : projet/src/image/io/image_ppm.cpp.i

projet/src/image/io/image_ppm.s: projet/src/image/io/image_ppm.cpp.s
.PHONY : projet/src/image/io/image_ppm.s

# target to generate assembly for a file
projet/src/image/io/image_ppm.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/io/image_ppm.cpp.s
.PHONY : projet/src/image/io/image_ppm.cpp.s

projet/src/image/ivec2.o: projet/src/image/ivec2.cpp.o
.PHONY : projet/src/image/ivec2.o

# target to build an object file
projet/src/image/ivec2.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/ivec2.cpp.o
.PHONY : projet/src/image/ivec2.cpp.o

projet/src/image/ivec2.i: projet/src/image/ivec2.cpp.i
.PHONY : projet/src/image/ivec2.i

# target to preprocess a source file
projet/src/image/ivec2.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/ivec2.cpp.i
.PHONY : projet/src/image/ivec2.cpp.i

projet/src/image/ivec2.s: projet/src/image/ivec2.cpp.s
.PHONY : projet/src/image/ivec2.s

# target to generate assembly for a file
projet/src/image/ivec2.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/ivec2.cpp.s
.PHONY : projet/src/image/ivec2.cpp.s

projet/src/lib/3d/vec3.o: projet/src/lib/3d/vec3.cpp.o
.PHONY : projet/src/lib/3d/vec3.o

# target to build an object file
projet/src/lib/3d/vec3.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/vec3.cpp.o
.PHONY : projet/src/lib/3d/vec3.cpp.o

projet/src/lib/3d/vec3.i: projet/src/lib/3d/vec3.cpp.i
.PHONY : projet/src/lib/3d/vec3.i

# target to preprocess a source file
projet/src/lib/3d/vec3.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/vec3.cpp.i
.PHONY : projet/src/lib/3d/vec3.cpp.i

projet/src/lib/3d/vec3.s: projet/src/lib/3d/vec3.cpp.s
.PHONY : projet/src/lib/3d/vec3.s

# target to generate assembly for a file
projet/src/lib/3d/vec3.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/vec3.cpp.s
.PHONY : projet/src/lib/3d/vec3.cpp.s

projet/src/lib/common/backtrace.o: projet/src/lib/common/backtrace.cpp.o
.PHONY : projet/src/lib/common/backtrace.o

# target to build an object file
projet/src/lib/common/backtrace.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/backtrace.cpp.o
.PHONY : projet/src/lib/common/backtrace.cpp.o

projet/src/lib/common/backtrace.i: projet/src/lib/common/backtrace.cpp.i
.PHONY : projet/src/lib/common/backtrace.i

# target to preprocess a source file
projet/src/lib/common/backtrace.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/backtrace.cpp.i
.PHONY : projet/src/lib/common/backtrace.cpp.i

projet/src/lib/common/backtrace.s: projet/src/lib/common/backtrace.cpp.s
.PHONY : projet/src/lib/common/backtrace.s

# target to generate assembly for a file
projet/src/lib/common/backtrace.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/backtrace.cpp.s
.PHONY : projet/src/lib/common/backtrace.cpp.s

projet/src/lib/common/basic_functions.o: projet/src/lib/common/basic_functions.cpp.o
.PHONY : projet/src/lib/common/basic_functions.o

# target to build an object file
projet/src/lib/common/basic_functions.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/basic_functions.cpp.o
.PHONY : projet/src/lib/common/basic_functions.cpp.o

projet/src/lib/common/basic_functions.i: projet/src/lib/common/basic_functions.cpp.i
.PHONY : projet/src/lib/common/basic_functions.i

# target to preprocess a source file
projet/src/lib/common/basic_functions.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/basic_functions.cpp.i
.PHONY : projet/src/lib/common/basic_functions.cpp.i

projet/src/lib/common/basic_functions.s: projet/src/lib/common/basic_functions.cpp.s
.PHONY : projet/src/lib/common/basic_functions.s

# target to generate assembly for a file
projet/src/lib/common/basic_functions.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/basic_functions.cpp.s
.PHONY : projet/src/lib/common/basic_functions.cpp.s

projet/src/lib/common/exception_cpe.o: projet/src/lib/common/exception_cpe.cpp.o
.PHONY : projet/src/lib/common/exception_cpe.o

# target to build an object file
projet/src/lib/common/exception_cpe.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/exception_cpe.cpp.o
.PHONY : projet/src/lib/common/exception_cpe.cpp.o

projet/src/lib/common/exception_cpe.i: projet/src/lib/common/exception_cpe.cpp.i
.PHONY : projet/src/lib/common/exception_cpe.i

# target to preprocess a source file
projet/src/lib/common/exception_cpe.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/exception_cpe.cpp.i
.PHONY : projet/src/lib/common/exception_cpe.cpp.i

projet/src/lib/common/exception_cpe.s: projet/src/lib/common/exception_cpe.cpp.s
.PHONY : projet/src/lib/common/exception_cpe.s

# target to generate assembly for a file
projet/src/lib/common/exception_cpe.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/exception_cpe.cpp.s
.PHONY : projet/src/lib/common/exception_cpe.cpp.s

projet/src/local/main.o: projet/src/local/main.cpp.o
.PHONY : projet/src/local/main.o

# target to build an object file
projet/src/local/main.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/local/main.cpp.o
.PHONY : projet/src/local/main.cpp.o

projet/src/local/main.i: projet/src/local/main.cpp.i
.PHONY : projet/src/local/main.i

# target to preprocess a source file
projet/src/local/main.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/local/main.cpp.i
.PHONY : projet/src/local/main.cpp.i

projet/src/local/main.s: projet/src/local/main.cpp.s
.PHONY : projet/src/local/main.s

# target to generate assembly for a file
projet/src/local/main.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/local/main.cpp.s
.PHONY : projet/src/local/main.cpp.s

projet/src/volume/transfert_function.o: projet/src/volume/transfert_function.cpp.o
.PHONY : projet/src/volume/transfert_function.o

# target to build an object file
projet/src/volume/transfert_function.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/volume/transfert_function.cpp.o
.PHONY : projet/src/volume/transfert_function.cpp.o

projet/src/volume/transfert_function.i: projet/src/volume/transfert_function.cpp.i
.PHONY : projet/src/volume/transfert_function.i

# target to preprocess a source file
projet/src/volume/transfert_function.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/volume/transfert_function.cpp.i
.PHONY : projet/src/volume/transfert_function.cpp.i

projet/src/volume/transfert_function.s: projet/src/volume/transfert_function.cpp.s
.PHONY : projet/src/volume/transfert_function.s

# target to generate assembly for a file
projet/src/volume/transfert_function.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/volume/transfert_function.cpp.s
.PHONY : projet/src/volume/transfert_function.cpp.s

projet/src/volume/volume.o: projet/src/volume/volume.cpp.o
.PHONY : projet/src/volume/volume.o

# target to build an object file
projet/src/volume/volume.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/volume/volume.cpp.o
.PHONY : projet/src/volume/volume.cpp.o

projet/src/volume/volume.i: projet/src/volume/volume.cpp.i
.PHONY : projet/src/volume/volume.i

# target to preprocess a source file
projet/src/volume/volume.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/volume/volume.cpp.i
.PHONY : projet/src/volume/volume.cpp.i

projet/src/volume/volume.s: projet/src/volume/volume.cpp.s
.PHONY : projet/src/volume/volume.s

# target to generate assembly for a file
projet/src/volume/volume.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/volume/volume.cpp.s
.PHONY : projet/src/volume/volume.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pgm"
	@echo "... rebuild_cache"
	@echo "... projet/src/image/color.o"
	@echo "... projet/src/image/color.i"
	@echo "... projet/src/image/color.s"
	@echo "... projet/src/image/image.o"
	@echo "... projet/src/image/image.i"
	@echo "... projet/src/image/image.s"
	@echo "... projet/src/image/image_zbuffer.o"
	@echo "... projet/src/image/image_zbuffer.i"
	@echo "... projet/src/image/image_zbuffer.s"
	@echo "... projet/src/image/io/image_ppm.o"
	@echo "... projet/src/image/io/image_ppm.i"
	@echo "... projet/src/image/io/image_ppm.s"
	@echo "... projet/src/image/ivec2.o"
	@echo "... projet/src/image/ivec2.i"
	@echo "... projet/src/image/ivec2.s"
	@echo "... projet/src/lib/3d/vec3.o"
	@echo "... projet/src/lib/3d/vec3.i"
	@echo "... projet/src/lib/3d/vec3.s"
	@echo "... projet/src/lib/common/backtrace.o"
	@echo "... projet/src/lib/common/backtrace.i"
	@echo "... projet/src/lib/common/backtrace.s"
	@echo "... projet/src/lib/common/basic_functions.o"
	@echo "... projet/src/lib/common/basic_functions.i"
	@echo "... projet/src/lib/common/basic_functions.s"
	@echo "... projet/src/lib/common/exception_cpe.o"
	@echo "... projet/src/lib/common/exception_cpe.i"
	@echo "... projet/src/lib/common/exception_cpe.s"
	@echo "... projet/src/local/main.o"
	@echo "... projet/src/local/main.i"
	@echo "... projet/src/local/main.s"
	@echo "... projet/src/volume/transfert_function.o"
	@echo "... projet/src/volume/transfert_function.i"
	@echo "... projet/src/volume/transfert_function.s"
	@echo "... projet/src/volume/volume.o"
	@echo "... projet/src/volume/volume.i"
	@echo "... projet/src/volume/volume.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

